import { useNavigate } from 'react-router-dom'
import Backdrop from '../components/Backdrop'
import Nav from '../components/Nav'

export default function Features() {
  const navigate = useNavigate()

  return (
    <div className="relative min-h-screen bg-void text-ink font-sans overflow-x-hidden">

      <Backdrop />
      <Nav active="features" />

      <div className="relative z-10 max-w-4xl mx-auto px-6 py-20">

        {/* Header */}
        <div className="text-center mb-16">
          <h1 className="font-display text-4xl md:text-5xl font-bold tracking-tight text-ink-bright mb-4">
            Features
          </h1>
          <p className="text-lg text-ink-dim max-w-xl mx-auto">
            Everything SATsec monitors, on every audit.
          </p>
        </div>

        {/* Main features */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
          {[
            {
              num: '01',
              title: 'Instant Audits',
              desc: 'Paste a URL. Get Performance, SEO, Accessibility, and Security in one scan.',
              tags: ['Lighthouse', 'axe-core', 'BeautifulSoup'],
              img: '/features/01-instant-audits.jpg',
            },
            {
              num: '02',
              title: 'Scheduled Monitoring',
              desc: 'Every 6 hours, daily, or weekly. Runs on your schedule, automatically.',
              tags: ['Every 6hrs', 'Daily', 'Weekly'],
              img: '/features/02-scheduled-monitoring.png',
            },
            {
              num: '03',
              title: 'Smart Alerts',
              desc: 'Emailed the moment a score drops below your threshold, with an explanation of what changed.',
              tags: ['Email alerts', 'Custom threshold', 'Instant'],
              img: '/features/03-smart-alerts.jpg',
            },
            {
              num: '04',
              title: 'Trend Dashboard',
              desc: 'Score history over time. Pinpoint exactly when a deploy broke your site.',
              tags: ['Score history', 'Deploy detection', 'Charts'],
              img: '/features/04-trend-dashboard.jpg',
            },
            {
              num: '05',
              title: 'ADA Compliance',
              desc: 'WCAG AA checks via axe-core. The same standard used in legal proceedings.',
              tags: ['WCAG AA', 'axe-core', 'Legal standard'],
              img: '/features/05-ada-compliance.jpg',
            },
            {
              num: '06',
              title: 'AI Summaries',
              desc: 'Every report ends with a plain-English summary generated by Claude.',
              tags: ['Claude AI', 'Plain English', 'Client ready'],
              img: '/features/06-ai-summaries.jpg',
            },
          ].map(({ num, title, desc, tags, img }) => (
            <div key={title} className="relative overflow-hidden panel hover:border-accent/20 transition-colors">
              <div
                className="h-32 w-full"
                style={{
                  backgroundImage: `linear-gradient(to bottom, rgba(5,8,13,0.3), rgba(5,8,13,0.9)), url(${img})`,
                  backgroundSize: 'cover',
                  backgroundPosition: 'center',
                }}
              />
              <div className="p-6 -mt-6 relative">
                <div className="font-mono text-xs text-accent mb-3">{num}</div>
                <h3 className="font-display text-base font-bold text-ink mb-2">{title}</h3>
                <p className="text-sm text-ink-dim leading-relaxed mb-4">{desc}</p>
                <div className="flex gap-2 flex-wrap">
                  {tags.map(tag => (
                    <span key={tag} className="text-xs bg-white/[0.04] border border-white/[0.08] text-ink-dim px-3 py-1 rounded-full font-mono">
                      {tag}
                    </span>
                  ))}
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Coming soon */}
        <div className="panel p-6 mb-10">
          <p className="eyebrow mb-4">Coming Soon</p>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
            {[
              'Multi-page Crawling',
              'Competitor Benchmarking',
              'ADA PDF Reports',
              'Slack Integration',
              'Deploy Diff Detection',
              'Chrome Extension',
            ].map(title => (
              <div key={title} className="flex items-center gap-3 bg-white/[0.02] border border-white/[0.04] rounded-xl px-4 py-3">
                <span className="font-mono text-xs text-accent/60">+</span>
                <span className="font-mono text-sm text-ink-faint">{title}</span>
              </div>
            ))}
          </div>
        </div>

        {/* CTA */}
        <div className="rounded-2xl border border-accent/20 bg-accent/[0.06] p-8 text-center">
          <h3 className="font-display text-xl font-bold text-ink-bright mb-2">Run your first audit.</h3>
          <p className="text-sm text-ink-faint mb-6">No signup. Results in seconds.</p>
          <button onClick={() => navigate('/')} className="btn-accent text-sm px-8 py-3">
            Run Audit →
          </button>
        </div>
      </div>
    </div>
  )
}