import { useNavigate } from 'react-router-dom'

export default function Features() {
  const navigate = useNavigate()

  return (
    <div className="min-h-screen bg-[#080c14] text-[#e8edf5] font-sans overflow-x-hidden">

      {/* Grid background */}
      <div className="fixed inset-0 z-0 pointer-events-none"
        style={{
          backgroundImage: 'linear-gradient(rgba(99,179,237,0.04) 1px, transparent 1px), linear-gradient(90deg, rgba(99,179,237,0.04) 1px, transparent 1px)',
          backgroundSize: '48px 48px'
        }}
      />

      {/* Nav */}
      <nav className="relative z-10 flex items-center justify-between px-12 py-5 border-b border-white/5">
        <div className="font-mono text-xl font-bold cursor-pointer" onClick={() => navigate('/')}>
          SAT<span className="text-blue-500">sec</span>
        </div>
        <div className="hidden md:flex gap-8">
          <span onClick={() => navigate('/features')} className="text-sm text-blue-400 cursor-pointer">Features</span>
          <span onClick={() => navigate('/dashboard')} className="text-sm text-[#8899aa] hover:text-[#e8edf5] transition-colors cursor-pointer">Dashboard</span>
          <span className="text-sm text-[#8899aa] hover:text-[#e8edf5] transition-colors cursor-pointer">Pricing</span>
          <span className="text-sm text-[#8899aa] hover:text-[#e8edf5] transition-colors cursor-pointer">Docs</span>
        </div>
        <button onClick={() => navigate('/')} className="bg-blue-500 hover:bg-blue-600 text-white text-sm font-medium px-5 py-2 rounded-lg transition-colors">
          Run Audit
        </button>
      </nav>

      <div className="relative z-10 max-w-4xl mx-auto px-6 py-20">

        {/* Header */}
        <div className="text-center mb-16">
          <h1 className="font-mono text-4xl md:text-5xl font-semibold tracking-tighter text-[#f0f4fa] mb-4">
            Features
          </h1>
          <p className="text-lg text-[#7a8fa8] font-light max-w-xl mx-auto">
            Everything SATsec monitors, on every audit.
          </p>
        </div>

        {/* Main features */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
          {[
            {
              num: '01',
              title: 'Instant Audits',
              desc: 'Paste a URL. Get Performance, SEO, Accessibility, and Security in one scan.',
              tags: ['Lighthouse', 'axe-core', 'BeautifulSoup'],
              img: '/features/01-instant-audits.jpg',
            },
            {
              num: '02',
              title: 'Scheduled Monitoring',
              desc: 'Every 6 hours, daily, or weekly. Runs on your schedule, automatically.',
              tags: ['Every 6hrs', 'Daily', 'Weekly'],
              img: '/features/02-scheduled-monitoring.png',
            },
            {
              num: '03',
              title: 'Smart Alerts',
              desc: 'Emailed the moment a score drops below your threshold, with an explanation of what changed.',
              tags: ['Email alerts', 'Custom threshold', 'Instant'],
              img: '/features/03-smart-alerts.jpg',
            },
            {
              num: '04',
              title: 'Trend Dashboard',
              desc: 'Score history over time. Pinpoint exactly when a deploy broke your site.',
              tags: ['Score history', 'Deploy detection', 'Charts'],
              img: '/features/04-trend-dashboard.jpg',
            },
            {
              num: '05',
              title: 'ADA Compliance',
              desc: 'WCAG AA checks via axe-core. The same standard used in legal proceedings.',
              tags: ['WCAG AA', 'axe-core', 'Legal standard'],
              img: '/features/05-ada-compliance.jpg',
            },
            {
              num: '06',
              title: 'AI Summaries',
              desc: 'Every report ends with a plain-English summary generated by Claude.',
              tags: ['Claude AI', 'Plain English', 'Client ready'],
              img: '/features/06-ai-summaries.jpg',
            },
          ].map(({ num, title, desc, tags, img }) => (
            <div key={title} className="relative overflow-hidden bg-white/[0.025] border border-white/[0.06] rounded-2xl hover:border-blue-500/20 transition-colors">
              <div
                className="h-32 w-full"
                style={{
                  backgroundImage: `linear-gradient(to bottom, rgba(8,12,20,0.3), rgba(8,12,20,0.9)), url(${img})`,
                  backgroundSize: 'cover',
                  backgroundPosition: 'center',
                }}
              />
              <div className="p-6 -mt-6 relative">
                <div className="font-mono text-xs text-blue-400 mb-3">{num}</div>
                <h3 className="font-mono text-base font-medium text-[#c8d8e8] mb-2">{title}</h3>
                <p className="text-sm text-[#5a7080] leading-relaxed mb-4">{desc}</p>
                <div className="flex gap-2 flex-wrap">
                  {tags.map(tag => (
                    <span key={tag} className="text-xs bg-white/[0.04] border border-white/[0.08] text-[#6a8099] px-3 py-1 rounded-full font-mono">
                      {tag}
                    </span>
                  ))}
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Coming soon */}
        <div className="bg-white/[0.025] border border-white/[0.06] rounded-2xl p-6 mb-10">
          <p className="text-xs font-mono text-[#8899aa] uppercase tracking-widest mb-4">Coming Soon</p>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
            {[
              'Multi-page Crawling',
              'Competitor Benchmarking',
              'ADA PDF Reports',
              'Slack Integration',
              'Deploy Diff Detection',
              'Chrome Extension',
            ].map(title => (
              <div key={title} className="flex items-center gap-3 bg-white/[0.02] border border-white/[0.04] rounded-xl px-4 py-3">
                <span className="font-mono text-xs text-blue-400/60">+</span>
                <span className="font-mono text-sm text-[#4a6070]">{title}</span>
              </div>
            ))}
          </div>
        </div>

        {/* CTA */}
        <div className="bg-blue-500/[0.06] border border-blue-500/20 rounded-2xl p-8 text-center">
          <h3 className="font-mono text-xl font-medium text-[#e8edf5] mb-2">Run your first audit.</h3>
          <p className="text-sm text-[#4a6070] mb-6">No signup. Results in seconds.</p>
          <button onClick={() => navigate('/')} className="bg-blue-500 hover:bg-blue-600 text-white text-sm font-mono font-medium px-8 py-3 rounded-lg transition-colors">
            Run Audit →
          </button>
        </div>
      </div>
    </div>
  )
}